image: "scorpil/rust:stable"

stages:
    - build
    - test

before_script:
    - apt-get install -y libudev-dev

build-debug:
    stage: build
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo build --verbose

build-release:
    stage: build
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo build --verbose --release

test:
    stage: test
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo test --verbose --jobs 1 --release # Don't parallelize to make errors more readable
