variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: apt-cache
    paths:
    - apt-cache/
    - cargo/
    - target/

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update && apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev
    - export PATH="~/.cargo/bin:$PATH"

test:1.13:
    image: "debian:testing"
    script:
    - export RUST_ARCHIVE=rust-1.13.0-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose

test:stable:
    image: "debian:testing"
    script:
    - export RUST_ARCHIVE=`curl https://static.rust-lang.org/dist/channel-rust-stable | grep x86_64-unknown-linux-gnu`
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose
    # Also run rustfmt checks on stable
    - cargo install rustfmt
    - cargo fmt -- --write-mode=diff

test:nightly:
    image: "debian:testing"
    allow_failure: true
    script:
    - export RUST_ARCHIVE=rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose
