variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: apt-cache
    paths:
    - apt-cache/
    - cargo/
    - target/

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update && apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev
    - export PATH="~/.cargo/bin:$PATH"

test:1.13:
    image: "debian:testing"
    script:
    - export RUST_ARCHIVE=rust-1.13.0-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose

test:stable:
    image: "debian:testing"
    script:
    # It's currently only possible to pull specific versions, not 'stable' directly.
    # See https://github.com/rust-lang/rust/issues/39571
    - export RUST_ARCHIVE=rust-1.15.0-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose

test:nightly:
    image: "debian:testing"
    script:
    - export RUST_ARCHIVE=rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose
