image: "scorpil/rust:stable"

stages:
    - build
    - test

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    APT_CACHE_DIR: apt-cache

cache:
    key: apt-cache
    paths:
        - apt-cache/
        - cargo/

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update && apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev

build-debug:
    stage: build
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo build --verbose

build-release:
    stage: build
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo build --verbose --release

test:
    stage: test
    script:
        - rustc --version && cargo --version # Print version info for debugging
        - cargo test --verbose --jobs 1 --release # Don't parallelize to make errors more readable
        - cargo install rustfmt --root rustfmt-bin || true
        - export PATH=$PATH:rustfmt-bin
        - cargo fmt -- --write-mode=diff
