variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: apt-cache
    paths:
    - apt-cache/
    - cargo/
    - target/

stages:
  - build
  - test
  - package

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev
    - export PATH="/root/.cargo/bin:$PATH"

build:stable:
    image: "debian:testing"
    stage: build
    script:
    - export RUST_ARCHIVE=`curl https://static.rust-lang.org/dist/channel-rust-stable | grep x86_64-unknown-linux-gnu`
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose

build:nightly:
    image: "debian:testing"
    allow_failure: true
    stage: build
    script:
    - export RUST_ARCHIVE=rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose

test:rustfmt:
    image: "debian:testing"
    stage: test
    script:
    - export RUST_ARCHIVE=`curl https://static.rust-lang.org/dist/channel-rust-stable | grep x86_64-unknown-linux-gnu`
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo install rustfmt
    - cargo fmt -- --write-mode=diff

test:clippy:
    image: "debian:testing"
    stage: test
    script:
    - export RUST_ARCHIVE=rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --verbose
    - cargo install clippy
    - cargo clippy -- --allow=cyclomatic_complexity

package:
    image: "debian:testing"
    artifacts:
      paths:
      - target/release/gattii
      name: "$CI_BUILD_REF_NAME"
    stage: package
    script:
    - export RUST_ARCHIVE=`curl https://static.rust-lang.org/dist/channel-rust-stable | grep x86_64-unknown-linux-gnu`
    - export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
    - curl -fsOSL $RUST_DOWNLOAD_URL
    - curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c -
    - tar -xzf $RUST_ARCHIVE --strip-components=1
    - ./install.sh
    - cargo build --release

